services:
  dilekce-uretici:
    build: ./backend/dilekce_uretici
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 app:app
    ports: ["8000:8000"]

  sozlesme-analizi:
    build: ./backend/sozlesme_analizi
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8001 app:app
    ports: ["8001:8001"]

  hukuki-chatbot:
    build: ./backend/hukuki_chatbot
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8002 app:app
    ports: ["8002:8002"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  frontend:
    build: ./frontend
    ports: ["3000:3000"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    ports: ["8080:80"]
    depends_on:
      - dilekce-uretici
      - sozlesme-analizi
      - hukuki-chatbot